import { useMemo, useState } from 'react'
import { Activity, ChevronDown, TerminalSquare } from 'lucide-react'
import { useProjectStore } from '../store/projectStore'

export function BottomPanel({ log }: { job?: any; log: string }) {
  const [collapsed, setCollapsed] = useState(false); const [tab, setTab] = useState<'orbitals' | 'log'>('orbitals'); const [unit, setUnit] = useState<'eV' | 'Eh'>('eV')
  const result = useProjectStore(s => s.result); const selected = useProjectStore(s => s.selectedOrbital); const setSelected = useProjectStore(s => s.setSelectedOrbital)
  const orbitals = useMemo(() => result?.orbitals ?? [], [result?.orbitals]); const range = useMemo(() => { if (!orbitals.length) return [-1, 1]; const e = orbitals.map(o => o.energy_hartree); return [Math.min(...e), Math.max(...e)] }, [orbitals]); const factor = unit === 'eV' ? 27.211386245988 : 1
  return <section className={`bottom-panel ${collapsed ? 'collapsed' : ''}`}><header><div className="bottom-tabs"><button className={tab === 'orbitals' ? 'active' : ''} onClick={() => setTab('orbitals')}><Activity /> MO 에너지</button><button className={tab === 'log' ? 'active' : ''} onClick={() => setTab('log')}><TerminalSquare /> 계산 로그</button></div><div className="result-summary">{result ? <><span><small>최종 총에너지</small><b>{result.total_energy_hartree.toFixed(8)} Eh</b></span><span><small>수렴</small><b className="converged">SCF · Geometry</b></span><span className="local-label">{result.local_minimum_notice}</span>{result.demo && <em>DEMO · 실제 계산 아님</em>}</> : <span>계산 결과 없음</span>}<button className="icon-button" onClick={() => setCollapsed(!collapsed)}><ChevronDown /></button></div></header>{!collapsed && <div className="bottom-content">{tab === 'log' ? <pre className="job-log">{log || '로그가 없습니다.'}</pre> : orbitals.length ? <div className="energy-diagram"><div className="energy-axis"><span>{(range[1] * factor).toFixed(1)}</span><span>{(((range[0] + range[1]) / 2) * factor).toFixed(1)}</span><span>{(range[0] * factor).toFixed(1)}</span><b>{unit}</b></div><div className="levels">{orbitals.map(o => { const y = 8 + (range[1] - o.energy_hartree) / Math.max(.0001, range[1] - range[0]) * 80; return <button key={o.internal_id} className={`level ${o.occupancy ? 'occupied' : 'virtual'} ${selected === o.internal_id ? 'selected' : ''}`} style={{ top: `${y}%` }} onClick={() => setSelected(o.internal_id)} title={`ORCA index ${o.orca_index}; 표시 번호 ${o.display_number}`}><i /><span>{o.label ?? `MO ${o.display_number}`}</span><small>{(o.energy_hartree * factor).toFixed(3)}</small></button>})}</div><div className="diagram-legend"><span><i className="occ" /> 점유</span><span><i className="virt" /> 비점유</span><button onClick={() => setUnit(unit === 'eV' ? 'Eh' : 'eV')}>{unit} → {unit === 'eV' ? 'Eh' : 'eV'}</button></div></div> : <div className="empty-diagram">오비탈 데이터가 없습니다. 계산이 전자구조 출력을 만들지 못했거나 아직 실행되지 않았습니다.</div>}</div>}</section>
}
